### ISSUE TITLE
Difference between http-server and http

### ISSUE THREAD

**Issue by iamdriz** [nodeapps/http-server#120]
What's the difference between this module and the http module that is part of Node core?

**Comment by indexzero** [comment]
The core Node.js `http` module (see: [API reference](http://nodejs.org/docs/latest/api/http.html)) is just that: a module to interact with HTTP in Javascript.

In contrast, `http-server` (see: [API reference](https://github.com/nodeapps/http-server#http-server-a-command-line-http-server)) is not meant to be used as a module, but as a stand-alone static file available via a CLI tool of the same name: `http-server`. In this way it is more comparable to other tools on the [Big list of http static server one-liners](https://gist.github.com/willurd/5720255).

If you're looking for a _module_ that can serve static files check out [`ecstatic`](https://github.com/jesusabdullah/node-ecstatic) (which is used by `http-server`), [`node-static`](https://github.com/cloudhead/node-static), or [`st`](https://github.com/isaacs/st).
