### ISSUE TITLE
Version 0.7.4 is not working well in window 7 64bit

### ISSUE THREAD

**Issue by caibinterry** [nodeapps/http-server#122]
I use it like this way : F:\createjs\easejs\EaselJS-master\examples>http-server 
but when i enter the link in my browser like this : localhost:8080
it does not work well , and show the information : Invalid forward slash character 
(i think it should list all the files/folders in current path)

i do not know the reason , so i using the version 0.7.0 now , it seems work well.

**Comment by anthwinter** [comment]
I have the same issue on Windows 8 (64 bit). It seems going to http://localhost:8080 will result in

    Error: Invalid forward slash character

But, going to http://localhost:8080/index.html will work.

To run my site,  I do the following:

    > http-server D:\my-site

Within that directory I have: index.html, style.css

**Comment by billti** [comment]
I just hit this also.  I believe I tracked this down to an issue in the "ecstatic" package.  I have a pull request out that fixes the issue for me ( https://github.com/jfhbrook/node-ecstatic/pull/131 ).  It's a very simply fix you could apply manually to see if this resolves the issue for you.

Note the package dependency will need the version updated if/when the ecstatic packge is fixed and published, as it's currently snapped to an older version in the package.json.

**Comment by salsaysal** [comment]
I have windows 7 64 and tried to use http-server 0.74, cos I already had node, but when browsing localhost:8080, instead of compiling the html, it downloads the html file, that I can open then but browser opens this: file:///C:/Users/gabriel/AppData/Local/Temp/AaWmhRTR

I guess I will have to install ngninx :(
